version: "3.7"

x-common-envs: &common-envs
    DOCKER_ENV: ${DOCKER_ENV:?It seems you forgot to set "DOCKER_ENV" in .env}

x-volumes-list:
    - &app-sources ${HOST_SRC_PATH}:${CONTAINER_SRC_PATH}
    - &storage ../storage:/var/www/storage
    - &logs ../logdna/php/app:/var/log/php/

x-debug-settings: &xdebug-settings
    XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
    XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT}
    XDEBUG_MODE: ${XDEBUG_MODE}
    XDEBUG_START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST}
    XDEBUG_TRIGGER: ${XDEBUG_TRIGGER}
    XDEBUG_LOG_FILE: ${XDEBUG_LOG_FILE}
    XDEBUG_LOG_LEVEL: ${XDEBUG_LOG_LEVEL}

services:
    nginx:
        image: nginx:alpine
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        working_dir: ${CONTAINER_SRC_PATH}
        networks:
            - docker_net
        environment:
            <<: *common-envs
        expose:
            - 443
            - 80
        ports:
            - "80:80"
        volumes:
            - *app-sources
            - ./nginx/assets/default.conf:/etc/nginx/conf.d/default.conf
        command: [ nginx-debug, '-g', 'daemon off;' ]

    php-fpm:
        build:
            context: ./php/fpm
            dockerfile: ./Dockerfile
            target: development
            args:
                PHP_VERSION: 7.4.18
        container_name: ${COMPOSE_PROJECT_NAME}_fpm
        working_dir: ${CONTAINER_SRC_PATH}
        networks:
            - docker_net
        environment:
            <<: *xdebug-settings
            <<: *common-envs
            TIMEZONE: ${TIMEZONE:-Europe/Minsk}
            CHANGE_UID: 1
            HOST_USER_ID: 1000
            XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
            PHP_IDE_CONFIG: "serverName=Docker"
        volumes:
            - *app-sources
            - *storage
            - *logs
            - composer-cache:/var/www/.composer
            - ./php/fpm/assets/php.ini:/usr/local/etc/php/conf.d/php.ini

    mysql:
        image: mysql:8
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        command: >
            --general-log=1
            --general-log-file=/var/log/mysql/query.log
            --sql-mode="NO_ENGINE_SUBSTITUTION"
        environment:
            <<: *common-envs
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - ./mysql/dump:/var/lib/mysql
        networks:
            - docker_net

volumes:
    composer-cache:
        name: ${COMPOSE_PROJECT_NAME}_composer_cache

networks:
    docker_net:
        name: ${COMPOSE_PROJECT_NAME}_network
        ipam:
            driver: default
